image: registry.gitlab.com/ubports/infrastructure/gitlab-ci-build/focal
variables:
  DEBIAN_FRONTEND: noninteractive

build-focal:
  stage: build
  script:
    - apt-get update
    - apt-get -y install git devscripts germinate debootstrap
    - git clone https://github.com/ubports/ubuntu-touch-meta.git build
    - cd build
    - git checkout ubports/focal
    - ./update
  cache:
    policy: push
    paths:
      - build

publish-focal:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "focal"'
  script:
    - apt-get update
    - apt-get -y install git
    - cd build
    - sed "s/UNRELEASED/focal/g" -i debian/changelog
    - git config --global user.email "developers@ubports.com"
    - git config --global user.name "UBports developers"
    - git add -A
    - git commit -m "Automatic germinate refresh from gitlab"
    - DISABLE_FORCE_PUSH=1 CI_COMMIT_SHA=HEAD git-push git@github.com:ubports/ubuntu-touch-meta.git ubports/focal
  cache:
    policy: pull
    paths:
      - build
