image: registry.gitlab.com/ubports/infrastructure/gitlab-ci-build/focal
variables:
  DEBIAN_FRONTEND: noninteractive
  UBUNTU_TOUCH_META_TOKEN: $UBUNTU_TOUCH_META_TOKEN

build-focal:
  stage: build
  script:
    - apt-get update
    - apt-get -y install git devscripts germinate debootstrap
    - git clone https://gitlab.com/ubports/core/ubuntu-touch-meta.git build
    - cd build
    - git checkout ubports/focal
    - ./update
  cache:
    policy: push
    paths:
      - build

publish-focal:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "focal"'
  script:
    - apt-get update
    - apt-get -y install git
    - cd build
    - sed "s/UNRELEASED/focal/g" -i debian/changelog
    - git config --global user.email "developers@ubports.com"
    - git config --global user.name "UBports developers"
    - git add -A
    - git commit -m "Automatic germinate refresh from ${CI_PROJECT_NAME} CI (${CI_COMMIT_SHORT_SHA})" || true
    - git push "https://ubuntu-touch-meta:${UBUNTU_TOUCH_META_TOKEN}@gitlab.com/ubports/core/ubuntu-touch-meta.git" ubports/focal
  cache:
    policy: pull
    paths:
      - build
