image: ubports/build-essential:bionic 

build-xenial:
  stage: build
  script:
    - git clone https://github.com/ubports/ubuntu-touch-meta.git build
    - cd build
    - git checkout ${CI_COMMIT_BRANCH} || git checkout xenial
    - 'echo "dist: ${CI_COMMIT_BRANCH}" >> update.cfg'
    - ./update
    - git checkout update.cfg
  cache:
    policy: push
    paths:
      - build

publish-xenial:
  stage: deploy
  image: ubports/git-push
  script:
    - cd build
    - sed "s/UNRELEASED/xenial/g" -i debian/changelog
    - git config --global user.email "developers@ubports.com"
    - git config --global user.name "UBports developers"
    - git add -A
    - git commit -m "Automatic germinate refresh from gitlab"
    - DISABLE_FORCE_PUSH=1 CI_COMMIT_SHA=HEAD git-push git@github.com:ubports/ubuntu-touch-meta.git ${CI_COMMIT_BRANCH}
  cache:
    policy: pull
    paths:
      - build
